# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

logo: assets/images/car.svg

service-layout: "third"

tagline: Site Tagline plus some text
call-to-action: Call to Action
section-1-image: assets/images/image-3.jpg
intro-image: assets/images/image-4.jpg

# Site settings
title: Business Title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/cw-master/_site" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
